/**********************************/
/* �e�[�u����: Javelin���O */
/**********************************/
CREATE TABLE JAVELIN_LOG(
  LOG_ID BIGINT DEFAULT NEXTVAL('SEQ_LOG_ID') NOT NULL,
  SESSION_ID BIGINT DEFAULT NEXTVAL('SEQ_SESSION_ID') NOT NULL,
  SEQUENCE_ID INT NOT NULL,
  JAVELIN_LOG BINARY NOT NULL,
  LOG_FILE_NAME VARCHAR,
  START_TIME TIMESTAMP,
  END_TIME TIMESTAMP,
  SESSION_DESC VARCHAR,
  LOG_TYPE INT,
  CALLEE_NAME VARCHAR,
  CALLEE_SIGNATURE VARCHAR,
  CALLEE_CLASS VARCHAR,
  CALLEE_FIELD_TYPE VARCHAR,
  CALLEE_OBJECTID INT,
  CALLER_NAME VARCHAR,
  CALLER_SIGNATURE VARCHAR,
  CALLER_CLASS VARCHAR,
  CALLER_OBJECTID INT,
  EVENT_LEVEL TINYINT,
  ELAPSED_TIME BIGINT,
  MODIFIER VARCHAR,
  THREAD_NAME VARCHAR,
  THREAD_CLASS VARCHAR,
  THREAD_OBJECTID INT,
  MEASUREMENT_ITEM_NAME VARCHAR
);

/**********************************/
/* �e�[�u����: Javelin�v������ */
/**********************************/
CREATE TABLE JAVELIN_MEASUREMENT_ITEM(
  MEASUREMENT_ITEM_ID INT DEFAULT NEXTVAL('SEQ_MEASUREMENT_ITEM_ID') NOT NULL,
  MEASUREMENT_TYPE INT NOT NULL,
  ITEM_NAME VARCHAR NOT NULL,
  LAST_INSERTED TIMESTAMP NOT NULL
);

/**********************************/
/* �e�[�u����: Javelin �v���l */
/**********************************/
CREATE TABLE MEASUREMENT_VALUE(
  MEASUREMENT_VALUE_ID BIGINT DEFAULT NEXTVAL('SEQ_VALUE_ID') NOT NULL,
  MEASUREMENT_NUM BIGINT NOT NULL,
  MEASUREMENT_TIME TIMESTAMP NOT NULL,
  MEASUREMENT_TYPE INT NOT NULL,
  MEASUREMENT_ITEM_ID INT,
  VALUE DECIMAL
);

/**********************************/
/* �e�[�u����: �v���l��� */
/**********************************/
CREATE TABLE MEASUREMENT_INFO(
  MEASUREMENT_TYPE INT NOT NULL,
  ITEM_NAME VARCHAR NOT NULL,
  DISPLAY_NAME VARCHAR NOT NULL,
  DESCRIPTION VARCHAR
);

/**********************************/
/* �e�[�u����: �v���Ώۃz�X�g��� */
/**********************************/
CREATE TABLE HOST_INFO(
  HOST_ID INT DEFAULT NEXTVAL('SEQ_HOST_ID') NOT NULL,
  HOST_NAME VARCHAR,
  IP_ADDRESS VARCHAR NOT NULL,
  PORT INT NOT NULL,
  DESCRIPTION VARCHAR
);

/**********************************/
/* �e�[�u����: Javelin �v���l�A�[�J�C�u */
/**********************************/
CREATE TABLE ARCHIVED_VALUE(
  MEASUREMENT_VALUE_ID BIGINT DEFAULT NEXTVAL('SEQ_VALUE_ID') NOT NULL,
  MEASUREMENT_NUM BIGINT NOT NULL,
  MEASUREMENT_TIME TIMESTAMP NOT NULL,
  MEASUREMENT_TYPE INT NOT NULL,
  MEASUREMENT_ITEM_ID INT,
  VALUE DECIMAL
);

/**********************************/
/* �e�[�u����: �V�O�i����`�e�[�u�� */
/**********************************/
CREATE TABLE SIGNAL_DEFINITION(
  SIGNAL_ID serial NOT NULL,
  SIGNAL_NAME VARCHAR NOT NULL UNIQUE,
  MATCHING_PATTERN VARCHAR NOT NULL,
  LEVEL INT NOT NULL,
  PATTERN_VALUE VARCHAR NOT NULL,
  ESCALATION_PERIOD DOUBLE PRECISION
);

/**********************************/
/* �e�[�u����: �}�b�v�e�[�u�� */
/**********************************/
CREATE TABLE MAP_INFO(
 MAP_ID SERIAL NOT NULL,
 NAME VARCHAR(64),
 DATA text,
 LAST_UPDATE TIMESTAMP NOT NULL
);

/**********************************/
/* �e�[�u����: ���|�[�g��`�e�[�u�� */
/**********************************/
CREATE TABLE REPORT_DEFINITION(
  REPORT_ID SERIAL NOT NULL,
  REPORT_NAME VARCHAR NOT NULL,
  TARGET_MEASUREMENT_NAME VARCHAR NOT NULL,
  FM_TIME VARCHAR NOT NULL,
  TO_TIME VARCHAR NOT NULL
);
CREATE TABLE SCHEDULING_REPORT_DEFINITION (
  REPORT_ID SERIAL PRIMARY KEY,
  REPORT_NAME  VARCHAR  ,
  TARGET_MEASUREMENT_NAME VARCHAR  ,
  SCHEDULE_TERM VARCHAR ,
  SCHEDULE_TIME VARCHAR  ,
  SCHEDULE_DAY VARCHAR  ,
  SCHEDULE_DATE VARCHAR	,
  LAST_EXPORT_REPORT_TIME VARCHAR	
);
/**********************************/
/* �e�[�u����: MULTIPLE_RESOURCE_GRAPH */
/**********************************/
CREATE TABLE MULTIPLE_RESOURCE_GRAPH(
  MULTIPLE_RESOURCE_GRAPH_ID SERIAL NOT NULL,
  MULTIPLE_RESOURCE_GRAPH_NAME VARCHAR NOT NULL,
  MEASUREMENT_ITEM_ID_LIST VARCHAR NOT NULL
);

/**********************************/
/* �e�[�u����: SQL_PLAN */
/**********************************/
CREATE TABLE SQL_PLAN(
  MEASUREMENt_ITEM_NAME VARCHAR NOT NULL,
  SQL_STATEMENT VARCHAR NOT NULL,
  EXECUTION_PLAN VARCHAR NOT NULL,
  GETTING_PLAN_TIME TIMESTAMP NOT NULL,
  STACK_TRACE TEXT NOT NULL,
  UNIQUE(MEASUREMENt_ITEM_NAME, EXECUTION_PLAN),
  UNIQUE(MEASUREMENt_ITEM_NAME, STACK_TRACE)
);

ALTER TABLE JAVELIN_LOG ADD PRIMARY KEY (LOG_ID);
CREATE INDEX IDX_JAVELIN_LOG_START_TIME ON JAVELIN_LOG (START_TIME);
CREATE INDEX IDX_JAVELIN_LOG_END_TIME ON JAVELIN_LOG (END_TIME);
CREATE INDEX IDX_JAVELIN_LOG_SESSION_ID ON JAVELIN_LOG (SESSION_ID);
CREATE INDEX IDX_JAVELIN_LOG_LOG_FILE_NAME ON JAVELIN_LOG (LOG_FILE_NAME);

ALTER TABLE JAVELIN_MEASUREMENT_ITEM ADD PRIMARY KEY (MEASUREMENT_ITEM_ID);

ALTER TABLE MEASUREMENT_VALUE ADD PRIMARY KEY (MEASUREMENT_VALUE_ID);
ALTER TABLE MEASUREMENT_VALUE ADD CONSTRAINT FK_MEASUREMENT_VALUE_0 FOREIGN KEY (MEASUREMENT_ITEM_ID) REFERENCES JAVELIN_MEASUREMENT_ITEM (MEASUREMENT_ITEM_ID);
CREATE INDEX IDX_MEASUREMENT_VALUE_MEASUREMENT_NUM ON MEASUREMENT_VALUE (MEASUREMENT_NUM);
CREATE INDEX IDX_MEASUREMENT_VALUE_MEASUREMENT_TIME ON MEASUREMENT_VALUE (MEASUREMENT_TIME, MEASUREMENT_TYPE);
CREATE INDEX IDX_MEASUREMENT_TYPE ON MEASUREMENT_VALUE (MEASUREMENT_TYPE);

ALTER TABLE MEASUREMENT_INFO ADD PRIMARY KEY (MEASUREMENT_TYPE);

ALTER TABLE HOST_INFO ADD PRIMARY KEY (HOST_ID);

ALTER TABLE ARCHIVED_VALUE ADD PRIMARY KEY (MEASUREMENT_VALUE_ID);
ALTER TABLE ARCHIVED_VALUE ADD CONSTRAINT FK_ARCHIVED_VALUE_0 FOREIGN KEY (MEASUREMENT_ITEM_ID) REFERENCES JAVELIN_MEASUREMENT_ITEM (MEASUREMENT_ITEM_ID);
CREATE INDEX IDX_ARCHIVED_VALUE_MEASUREMENT_NUM ON ARCHIVED_VALUE (MEASUREMENT_NUM);
CREATE INDEX IDX_ARCHIVED_VALUE_MEASUREMENT_TIME ON ARCHIVED_VALUE (MEASUREMENT_TIME, MEASUREMENT_TYPE);

ALTER TABLE MAP_INFO ADD PRIMARY KEY (MAP_ID);

ALTER TABLE SQL_PLAN ADD PRIMARY KEY (MEASUREMENT_ITEM_NAME);

CREATE INDEX IDX_SQL_PLAN_SESSION_ID ON SQL_PLAN (MEASUREMENt_ITEM_NAME);
